RealEstateProject/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RealEstateProject.Models
{
    [Table("Branch_tbl")]
    public class Branch
    {
        [Key]
        public String BranchNo { get; set; }
        public String Street { get; set; }
        public String City { get; set; }
        public String Postcode { get; set; }

        public virtual List<Rent> rents { get; set; }
        public virtual List<Staff> staffs { get; set; }
    }
}

RealEstateProject/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RealEstateProject.Models;

namespace RealEstateProject.Controllers
{
    public class BranchController : Controller
    {
        // GET: Branch
        private RealEstateContext realEstateContext = new RealEstateContext();
        public ActionResult Index()
        {
            List<Branch> AllBranches = realEstateContext.branches.ToList();
            return View(AllBranches);
        }

        public ActionResult Create()//Load
        { //Dropdown list 
            ViewBag.BranchDetails = realEstateContext.branches;
            return View();

        }
        [HttpPost]
        public ActionResult Create(Branch branch)//Insert
        {
            ViewBag.BranchDetails = realEstateContext.branches;
            realEstateContext.branches.Add(branch);
            realEstateContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(String id)
        {
            Branch branch = realEstateContext.branches.SingleOrDefault(x => x.BranchNo == id);
            return View(branch);
        }

        public ActionResult Edit(String id)
        {
            Branch branch = realEstateContext.branches.SingleOrDefault(x => x.BranchNo == id);
            ViewBag.BranchDetails = new SelectList(realEstateContext.branches);
            return View(branch);
        }
        [HttpPost]
        public ActionResult Edit(String id, Branch updatedBranch)
        {
            Branch branch = realEstateContext.branches.SingleOrDefault(x => x.BranchNo == id);
            branch.Street = updatedBranch.Street;
            branch.City = updatedBranch.City;
            branch.Postcode = updatedBranch.Postcode;
            realEstateContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String id)
        {
            Branch branch = realEstateContext.branches.SingleOrDefault(x => x.BranchNo == id);
            return View(branch);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteBranch(String id)
        {
            Branch branch = realEstateContext.branches.SingleOrDefault(x => x.BranchNo == id);
            realEstateContext.branches.Remove(branch);
            realEstateContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BranchCount()
        {
            List<Branch> branch = realEstateContext.branches.ToList();
            return View(branch);
        }
    }
}

RealEstateProject/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RealEstateProject.Models;

namespace RealEstateProject.Controllers
{
    public class RentController : Controller
    {
        // GET: Rent
        private RealEstateContext realEstateContexts = new RealEstateContext();
        public ActionResult Index()
        {
            List<Rent> AllRents = realEstateContexts.rents.ToList();
            return View(AllRents);
        }

        public ActionResult Create()//Load
        { //Dropdown list 
            ViewBag.OwnerDetails = realEstateContexts.owners;
            ViewBag.StaffDetails = realEstateContexts.staffs;
            ViewBag.BranchDetails = realEstateContexts.branches;
            return View();

        }
        [HttpPost]
        public ActionResult Create(Rent rent)//Insert
        {
            ViewBag.OwnerDetails = realEstateContexts.owners;
            ViewBag.StaffDetails = realEstateContexts.staffs;
            ViewBag.BranchDetails = realEstateContexts.branches;
            realEstateContexts.rents.Add(rent);
            realEstateContexts.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(String id)
        {
            Rent rent = realEstateContexts.rents.SingleOrDefault(x => x.PropertyNo == id);
            return View(rent);
        }

        public ActionResult Edit(String id)
        {
            Rent rent = realEstateContexts.rents.SingleOrDefault(x => x.PropertyNo == id);
            ViewBag.OwnerDetails = new SelectList(realEstateContexts.owners, "OwnerNo", "OwnerNo");
            ViewBag.StaffDetails = new SelectList(realEstateContexts.staffs, "StaffNo", "StaffNo");
            ViewBag.BranchDetails = new SelectList(realEstateContexts.branches, "BranchNo", "BranchNo");
            return View(rent);
        }
        [HttpPost]
        public ActionResult Edit(String id, Rent updatedRent)
        {
            Rent rent = realEstateContexts.rents.SingleOrDefault(x => x.PropertyNo == id);
            rent.Street = updatedRent.Street;
            rent.City = updatedRent.City;
            rent.Ptype = updatedRent.Ptype;
            rent.Rooms = updatedRent.Rooms;
            rent.RefOwnerNo = updatedRent.RefOwnerNo;
            rent.RefStaffNo = updatedRent.RefStaffNo;
            rent.RefBranchNo = updatedRent.RefBranchNo;
            rent.Rent1 = updatedRent.Rent1;
            realEstateContexts.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String id)
        {
            Rent rent = realEstateContexts.rents.SingleOrDefault(x => x.PropertyNo == id);
            return View(rent);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteRent(String id)
        {
            Rent rent = realEstateContexts.rents.SingleOrDefault(x => x.PropertyNo == id);
            realEstateContexts.rents.Remove(rent);
            realEstateContexts.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult City()
        {
            List<Rent> CityName= realEstateContexts.rents.ToList();

            return View(CityName);
        }

        public ActionResult Property(String id)
        {
            List<Rent> PropertyNo = realEstateContexts.rents.Where(x => x.City == id).ToList();
            return View(PropertyNo);
        }
        public ActionResult PropertyDetails(String id)//action for get details of individual
        {
            Rent rent = realEstateContexts.rents.SingleOrDefault(x => x.PropertyNo == id);
            return View(rent);
        }

        public ActionResult BuildingCount(String id)
        {
            List<Rent> building = realEstateContexts.rents.Where(x => x.RefBranchNo == id).ToList();
            return View(building);
        }
    }
}

RealEstateProject/Views/Branch/BranchCount.cshtml
@model IEnumerable<RealEstateProject.Models.Branch>
@using RealEstateProject.Models

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Branch</title>
</head>
<body style="background-color:gainsboro">
    <div style="color:darkcyan;font-size:20px">
        <h1 style="color:crimson"><u>Branch Number</u></h1>
        @foreach (Branch branch in Model)
            {
            @Html.ActionLink(branch.BranchNo, "BuildingCount", "Rent", new { @id = branch.BranchNo }, null)
            <br />
        }
    </div>
</body>
</html>

RealEstateProject/Views/Branch/Create.cshtml
@model RealEstateProject.Models.Branch

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> Branch Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        <center>
        <div class="form-horizontal">
            <h4 style="color:red;font-size:30px">Branch</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group" style="color:mediumvioletred;font-size:25px">
                @Html.LabelFor(model => model.BranchNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10"style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.BranchNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BranchNo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group" style="color:mediumvioletred;font-size:25px">
                @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group" style="color:mediumvioletred;font-size:25px">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group" style="color:mediumvioletred;font-size:25px">
                @Html.LabelFor(model => model.Postcode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.Postcode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Postcode, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default "  style="color:darkblue;font-size:20px"/>
                </div>
            </div>
        </div>
        </center>
    }
    <center>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
        </center>
</body>
</html>

RealEstateProject/Views/Branch/Delete.cshtml
@model RealEstateProject.Models.Branch

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Branch</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Street)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Street)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Postcode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Postcode)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

RealEstateProject/Views/Branch/Details.cshtml
@model RealEstateProject.Models.Branch

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <style>
        body {
            background-color: lavender;
        }

        h4 {
            color: red;
            font-size: 30px;
            text-align: center;
        }

        dt {
            color: mediumvioletred;
            font-size: 25px;
        }

        dd {
            color: darkblue;
            font-size: 20px;
        }

        p {
            color: maroon;
            text-align: left;
            font-size: 30px;
        }
    </style>
</head>
<body>
    <div>
        <h4>Branch</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.BranchNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BranchNo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Street)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Street)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Postcode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Postcode)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.BranchNo })        
    </p>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

RealEstateProject/Views/Branch/Edit.cshtml
@model RealEstateProject.Models.Branch

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body style="background-color:lavender">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <center>
        <div class="form-horizontal" >
            <h4 style="color:red;font-size:30px">Branch</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.BranchNo)
    
            <div class="form-group" style="color:mediumvioletred;font-size:25px">
                @Html.LabelFor(model => model.BranchNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.BranchNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BranchNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="color:mediumvioletred;font-size:25px" >
                @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10"style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group" style="color:mediumvioletred;font-size:25px">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group" style="color:mediumvioletred;font-size:25px">
                @Html.LabelFor(model => model.Postcode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="color:mediumvioletred;font-size:20px">
                    @Html.EditorFor(model => model.Postcode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Postcode, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" style="color:darkblue;font-size:20px" />
                </div>
            </div>
        </div>
            </center>
    }
    <center>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </center>
</body>
</html>

RealEstateProject/Views/Branch/Index.cshtml
@model IEnumerable<RealEstateProject.Models.Branch>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table" border="1">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Postcode)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Postcode)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.BranchNo }) |
                @Html.ActionLink("Details", "Details", new { id=item.BranchNo }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.BranchNo })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>